# For more on configuring pre-commit hooks (see https://pre-commit.com/)

# Force all unspecified python hooks to run python 3.8
default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    additional_dependencies: ['click~=8.1']
    args:
    - "--line-length=99"
    - "--target-version=py38"
  - id: black
    alias: black-check
    stages: [manual]
    additional_dependencies: ['click~=8.1']
    args:
    - "--line-length=99"
    - "--target-version=py38"
    - "--check"
    - "--diff"
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
  - id: flake8
    alias: flake8-check
    stages: [manual]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy
    args: [--show-error-codes, --ignore-missing-imports, --explicit-package-bases, --warn-unused-ignores]
    files: ^dbt/adapters/.*
    language: system
  - id: mypy
    alias: mypy-check
    stages: [manual]
    args: [--show-error-codes, --pretty, --ignore-missing-imports, --explicit-package-bases]
    files: ^dbt/adapters
    language: system
