version: '3'
services:
  iris:
    image: intersystemsdc/iris-community
    command:
      - -a
      - iris session iris -U %SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    ports:
      - 1972:1972
      - 52773:52773
