version: '3'
services:
  iris:
    build: .
    command:
      - -a
      # by default it starts with a requirement to change passwords for system users
      - iris session iris -U %SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    ports:
      - 1975:1972
      - 52775:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
