# **what?**
# Runs code quality checks, unit tests, and verifies python build on
# all code commited to the repository. This workflow should not
# require any secrets since it runs for PRs from forked repos.
# By default, secrets are not passed to workflows running from
# a forked repo.

# **why?**
# Ensure code for dbt meets a certain quality standard.

# **when?**
# This will run for all PRs, when code is pushed to a release
# branch, and when manually triggered.

name: Tests and Code Checks

on:
  push:
    branches:
      - "main"
      - "develop"
      - "*.latest"
      - "releases/*"
  pull_request:
  workflow_dispatch:

permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  code-quality:
    name: code-quality

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install pre-commit
          pip install mypy==0.782
          pip install https://github.com/intersystems-community/intersystems-irispython/releases/download/3.4.1/intersystems_iris-3.4.1-py3-none-any.whl
          pip install -r requirements-dev.txt
          pip --version
          pre-commit --version
          mypy --version
          dbt --version

      - name: Run Tests
        run: tox -e py3{7,8,9,10}

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure

  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: install dependencies
        run: |
          pip install tox
      - name: Build Docker image
        run: docker build -t dbt-iris:$GITHUB_SHA .
      - name: Run Container
        run: |
          docker run --rm -d -p 1972:1972 dbt-iris:$GITHUB_SHA \
          -a 'iris session iris -U %SYS "##class(Security.Users).UnExpireUserPasswords(\"*\")"'
      - name: Run Tests
        run: tox -e py3{7,8,9,10}-iris

  build:
    needs:
      - code-quality
      - test-build
    name: build packages

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: |
          pip install --user --upgrade pip
          pip install --upgrade setuptools wheel twine check-wheel-contents tox
          pip --version

      - name: Build distributions
        run: |
          ./scripts/build-dist.sh

      - name: Show distributions
        run: ls -lh dist/

      - name: Check distribution descriptions
        run: |
          twine check dist/*
      - name: Check wheel contents
        run: |
          check-wheel-contents dist/*.whl --ignore W007,W008,W009
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
